window["importedZvoogSchedule"]={"title":"keys 1"
	 ,"tracks":[{"title":"drums","voices":[]
			 ,"effects":[
				{"pluginEffect":null,"kind":"gain","initial":"","parameters":[{"points":[{"skipMeasures":0,"skip384":0,"velocity":119}]}]}
				]}
		 ,{"title":"bass","voices":[]
			 ,"effects":[{"pluginEffect":null,"kind":"gain","initial":"","parameters":[{"points":[{"skipMeasures":0,"skip384":0,"velocity":119}]}]}]}
		 ,{"title":"lead","voices":[
				 {"measureChords":[]
					 ,"source":{"pluginSource":null,"kind":"wafinstrument","initial":"3","parameters":[]}
					 ,"effects":[{"pluginEffect":null,"kind":"gain","initial":"","parameters":[
						 {"points":[{"skipMeasures":0,"skip384":0,"velocity":55}]}]}
							,{"pluginEffect":null,"kind":"equalizer","initial":"","parameters":[
								{"points":[{"skipMeasures":0,"skip384":0,"velocity":78}]}
								,{"points":[{"skipMeasures":0,"skip384":0,"velocity":99}]}
								,{"points":[{"skipMeasures":0,"skip384":0,"velocity":88}]}
								,{"points":[{"skipMeasures":0,"skip384":0,"velocity":54}]}
								,{"points":[{"skipMeasures":0,"skip384":0,"velocity":96}]}
								,{"points":[{"skipMeasures":0,"skip384":0,"velocity":99}]}
								,{"points":[{"skipMeasures":0,"skip384":0,"velocity":60}]}
								,{"points":[{"skipMeasures":0,"skip384":0,"velocity":84}]}
								,{"points":[{"skipMeasures":0,"skip384":0,"velocity":42}]}
								,{"points":[{"skipMeasures":0,"skip384":0,"velocity":72}]}]}
					 ],"bass":false,"title":"Strum guitar","stringPattern":{
						strings: [
							'--*-----*-----*---*-----*-----*-',
							'----*-----*---------*-----*-----',
							'------*-----*---------*-----*---',
							'----------------*---------------',
							'*-------------------------------',
							'--------------------------------'
						]
					 },"keyPattern":null,"strumPattern":null}
			 ]
			 ,"effects":[{"pluginEffect":null,"kind":"gain","initial":"","parameters":[{"points":[{"skipMeasures":0,"skip384":0,"velocity":119}]}]}]}
		 ,{"title":"pad","voices":[],"effects":[{"pluginEffect":null,"kind":"gain","initial":"","parameters":[{"points":[{"skipMeasures":0,"skip384":0,"velocity":119}]}]}]}
	 ]
	 ,"effects":[
		{"pluginEffect":null,"kind":"echo","initial":"","parameters":[{"points":[{"skipMeasures":0,"skip384":0,"velocity":29.75}]}
			,{"points":[{"skipMeasures":0,"skip384":0,"velocity":59.5}]},{"points":[{"skipMeasures":0,"skip384":0,"velocity":107.10000000000001}]}
			,{"points":[{"skipMeasures":0,"skip384":0,"velocity":59.5}]},{"points":[{"skipMeasures":0,"skip384":0,"velocity":2.38}]}
			,{"points":[{"skipMeasures":0,"skip384":0,"velocity":29.75}]}]}
		,{"pluginEffect":null,"kind":"gain","initial":"","parameters":[{"points":[{"skipMeasures":0,"skip384":0,"velocity":119}]}]}
		]
	,"measures":[{"meter":{"count":4,"division":4},"tempo":120}]
	,"harmony":{"tone":"E","mode":"Ionian","progression":[
		{"duration":{"count":1,"division":1},"chord":"E"}
	]}
};
 